version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  publish:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm publish
workflows:
    build-and-test:
      jobs:
        - publish